### PR TITLE
Feature/req1.8

### PR DESCRIPTION
**Pull request by skatulich**

### CODE REVIEW

**Review by kouissar — APPROVED** [review]
It's looking good. I have few questions though: 
What are we doing with these config bits, for example if TestHarnessSlideNumber=10 and developer creates a 12 slides presentation, what happens then? If we set LogToFile=false, what does it mean? Just few questions to engage the debate.

**Comment by kemaric** [comment]
@kouissar I would think that the TestHarnessSlideNumber would be the limit on the TestSlide class slides. So you it would have the user run through a max number of  "TestHarnessSlideNumber"  TestSlides that were developed. Developers can make hundreds of slides, but only `TestHarnessSlideNumber` would get played, including ordered TestSlides.

**Comment by skatulich** [comment]
Kemari is correct.  On load the configuration file is loaded and based on the number of slides in the configuration file, the system would only display that many slides.  Also, if the log to file is set to false then no errors would be logged.  I figured this is a feature that would be set to true the majority of the time but could be configurable.

**Comment by skatulich** [comment]
Need another approval.

**Review by rpaudyal4769 — APPROVED** [review]

**Review by kemaric — APPROVED** [review]

**Pull request merged**
